#!/usr/bin/env python3
"""Merge ``local_items.yaml`` with ``ingest/last_jira_currentUser.json`` -> ``items.yaml``, then render the board.

Expected input: JSON from Jira search with a top-level ``issues`` array (same shape as the API).
JQL for exports is documented in ``ingest/QUERY_PACKS.md`` (source of truth); this script does not call Jira.

This file is kept as a thin wrapper over :mod:`scripts.sources.jira` so the historical
``.venv/bin/python scripts/refresh_from_jira.py`` command still works. For the full
daily multi-source refresh (Jira + Slack + Calendar/Gemini + Confluence), use
``.venv/bin/python scripts/daily_refresh.py`` (or ``make daily``).
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import yaml

BACKLOG_DIR = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = Path(__file__).resolve().parent

sys.path.insert(0, str(SCRIPTS_DIR))
from sources import jira as jira_source  # noqa: E402

LOCAL_FILE = BACKLOG_DIR / "local_items.yaml"
INGEST_DIR = BACKLOG_DIR / "ingest"
JIRA_EXPORT = INGEST_DIR / "last_jira_currentUser.json"
ITEMS_FILE = BACKLOG_DIR / "items.yaml"
RENDER_SCRIPT = SCRIPTS_DIR / "render_board.py"


def local_item_included_in_backlog(item: dict) -> bool:
    if item.get("front") == "other" and item.get("status") == "done":
        return False
    return True


def main() -> None:
    if not JIRA_EXPORT.is_file():
        print(f"Missing {JIRA_EXPORT}", file=sys.stderr)
        sys.exit(1)

    jira_items, jira_skipped = jira_source.load_items(INGEST_DIR)

    local_items: list = []
    if LOCAL_FILE.is_file():
        loc = yaml.safe_load(LOCAL_FILE.read_text(encoding="utf-8")) or {}
        local_items = loc.get("items") or []
    local_before = len(local_items)
    local_items = [x for x in local_items if local_item_included_in_backlog(x)]
    local_skipped = local_before - len(local_items)

    out = {"version": 1, "items": local_items + jira_items}

    header = """# Personal / program backlog -- system of record for Kanban + fronts.
# Jira rows are regenerated by scripts/refresh_from_jira.py (ids: jira-KEY).
# Local-only rows live in local_items.yaml.
# For Slack / Calendar+Gemini / Confluence ingest, run scripts/daily_refresh.py.
# Regenerate BOARD.md: .venv/bin/python scripts/render_board.py

"""

    ITEMS_FILE.write_text(
        header + yaml.dump(out, sort_keys=False, allow_unicode=True, width=100),
        encoding="utf-8",
    )
    skip_note = []
    if jira_skipped:
        skip_note.append(f"{jira_skipped} Jira skipped (other+done)")
    if local_skipped:
        skip_note.append(f"{local_skipped} local skipped (other+done)")
    extra = ("; " + ", ".join(skip_note)) if skip_note else ""
    print(f"Wrote {len(local_items)} local + {len(jira_items)} Jira -> {ITEMS_FILE}{extra}")

    subprocess.run([sys.executable, str(RENDER_SCRIPT)], check=True)


if __name__ == "__main__":
    main()
